version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./examples/${DATABASE_NAME}.sql:/docker-entrypoint-initdb.d/zoo.sql
    environment:
      - DATABASE_NAME=zoo
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
